variables:
    - name: azureSubscription
      value: dev-service-connection
    - name: resourceGroup
      value: deployent-rsg
    - name: deploymentParameters
      value: >-
        someOther=value
      #  identityClientId=$servicePrincipalId
      #  identityClientSecret=$servicePrincipalKey
    - name: environment
      value: dev